/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var FIBBONACCI_MAX = 4000000;
var total = 0;
var fib_prev = 1;
var fib_cur = 2;

while(fib_cur < FIBBONACCI_MAX){
    
    if( fib_cur % 2 == 0){
        total += fib_cur;
    }
    var new_fib = fib_prev + fib_cur;
    fib_prev = fib_cur;
    fib_cur = new_fib;
}

console.log("The total is: " + total);

